SELECT * FROM INFORMATION_SCHEMA.TABLES

SELECT * FROM INFORMATION_SCHEMA.TABLES
where TABLE_SCHEMA = 'sales'

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE [TABLE_SCHEMA] = 'Person'
AND [TABLE_NAME] = 'Person'

SELECT * FROM AdventureWorks2019.Sales.Store
/* DBO SCHIMA PADRÃO */
/* SELECT * from [Nome_Da_Base].[Nome_do_Schima].[Nome_Da_Tabela] */