/* DML - DATA MANUPULATION LANGUAGE 
SELECT, UPDATE, DELETE, INSERT, MERGE BULK INSERT
DQL - DATE QUERY LANGUAGE

DDL - DATE DEFINITION LANGUAGE
    CREATE,ALTER,DROP,TRUNCATE,DISABLE,TRIGGER, ENABLE,TRIGGER, UPDATE STATISTICS

DCL - DATE CONTROL LANGUAGE
GRANT, REVOKE, DENY

TCL - TRANSACTIONAL CONTROL LANGUAGE
BEGIN TRANSACTION, COMMIT, ROLLBACK

*/