/* 
OPERADORES
UNION (UNIÃO DOS VALORES DISTINTOS)
UNION ALL (UNIÃO COM TODOS OS VALORES, INCLUSIVE OS DUPLICADOS)
 */

 SELECT 'DEVDOJO' AS [NOME],
        'JAVA' AS [LINGUAGEM]
UNION
SELECT 'Google' as [empresa],
        'Kotlin' as [Tipo]

UNION ALL

 SELECT 'DEVDOJO' AS [NOME],
        'JAVA' AS [LINGUAGEM]